#!/usr/bin/perl -w
# ©2015 Red Lion Controls, Inc. All rights reserved. Red Lion, the Red Lion logo and Sixnet are registered trademarks of Red Lion Controls, Inc. All other company and product names are trademarks of their respective owners.


system("killall jbmcontrol");
system("killall gwlnx");

system("rm -f /tmp/log*");
system("rm -f /tmp/*.bin");
system("rm -f /tmp/*.zip");

print "Expires: Mon, 26 Jul 1997 05:00:00 GMT\n"
.     "Last-Modified: " . gmtime(time()) . " GMT\n"
.     "Cache-Control: no-store, no-cache, must-revalidate\n"
.     "Cache-Control: post-check=0, pre-check=0\n"
.     "Pragma: no-cache\n"
.     "Content-type: text/plain\n\n"

.     "SUCCESS\n";

exit(0);

