#!/usr/bin/perl -w
# ©2015 Red Lion Controls, Inc. All rights reserved. Red Lion, the Red Lion logo and Sixnet are registered trademarks of Red Lion Controls, Inc. All other company and product names are trademarks of their respective owners.

###############################################################################################################################
#                                                                                                                             #
# listgwapp - Get the list of all running gwlnx                                                                                     #
#                                                                                                                             #
###############################################################################################################################

$psauxHeader = `ps aux | grep COMMAND | grep -v grep 2>&1`;

$gwlnxList = `ps aux | grep gwlnx | grep -v grep 2>&1`;

print "Expires: Mon, 26 Jul 1997 05:00:00 GMT\n";
print "Last-Modified: " . gmtime(time()) . " GMT\n";
print "Cache-Control: no-store, no-cache, must-revalidate\n";
print "Cache-Control: post-check=0, pre-check=0\n";
print "Pragma: no-cache\n";
print "Content-type: text/html; charset=utf8\n\n";


print "$psauxHeader";

print "$gwlnxList";

exit(0);
 
