#!/usr/bin/perl -w
# ©2015 Red Lion Controls, Inc. All rights reserved. Red Lion, the Red Lion logo and Sixnet are registered trademarks of Red Lion Controls, Inc. All other company and product names are trademarks of their respective owners.

###############################################################################################################################
#                                                                                                                             #
# getgwlnxpid - Get list of gwlnx process ID                                                                                  #
#                                                                                                                             #
# For the record . .                                                                                                          #
#                                                                                                                             #
# All rights reserved.  No part of this program may be reproduced, stored in a retrieval system or transmitted, in any form   #
# or by any means, including but not limited to electronic, mechanical, photocopying, recording, or otherwise, without the    #
# express prior written consent of Sixnet, 4645 LaGuardia, St. Louis, MO 63134.  (314) 426-7781, fx: (314) 426-0007.          #
# Contact support@sixnet.com                                                                                                  #
#                                                                                                                             #
###############################################################################################################################

# Get the list of all the processID that is running gwlnx:

print "Expires: Mon, 26 Jul 1997 05:00:00 GMT\n";
print "Last-Modified: " . gmtime(time()) . " GMT\n";
print "Cache-Control: no-store, no-cache, must-revalidate\n";
print "Cache-Control: post-check=0, pre-check=0\n";
print "Pragma: no-cache\n";
print "Content-type: text/html; charset=utf8\n\n";

my $cmdStr = "/sbin/pidof gwlnx 2>&1 |";

if (!open(FILE, $cmdStr))
  {
   print "Unable to get PID.\n";

   exit;
  }

my $pidlist = <FILE>;

@pid = split(/\s+/, $pidlist);

foreach (@pid)     
       {                       
         chomp($_);      
         print $_ . "::";
       }      

close(FILE);

exit;

